In [1]:
import numpy as np

In [2]:
#1
print(np.__version__)

1.19.2


In [4]:
#2
a = [12.23, 13.32, 100, 36.32]
a = np.array(a,ndmin=1)
print(a)

[ 12.23  13.32 100.    36.32]


In [7]:
#3
a =np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
#4
a = np.zeros(10)
a[6] = 11
print(a)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [13]:
#5
a = np.arange(12,38)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [14]:
#6
a = a[::-1]
print(a)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [15]:
#7
a = np.array([1,2,3,4],dtype='float32')
print(a)

[1. 2. 3. 4.]


In [19]:
#8
a = np.zeros((5,5))
a[0,:] = 1
a[-1,:] = 1
a[:,0] = 1
a[:,-1] = 1
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
#9
x = np.ones((3,3))
print(x)
print()
x = np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
#10
a = np.array([0,1,0,1,0,1,0,1],ndmin=2)
print(a)

[[0 1 0 1 0 1 0 1]]


In [3]:
#11
l=[1,2,3,4,5,6,7,8]
t=(8,4,6,1,2,3)
a1=np.array(l)
a2=np.array(t).reshape(2,3)
print(a1,'\n',a2)

[1 2 3 4 5 6 7 8] 
 [[8 4 6]
 [1 2 3]]


In [4]:
#12
original=[10,20,30]
a=np.append(original,[40,50,60,70,80,90])
print(a)

[10 20 30 40 50 60 70 80 90]


In [9]:
#13
empty=np.empty((3,4),dtype='float')
full=np.full((3,3),6)
print(empty,'\n',full)

[[6.23042070e-307 8.45590538e-307 7.56593017e-307 8.01097889e-307]
 [1.78020169e-306 7.56601165e-307 1.02359984e-306 1.42417221e-306]
 [1.37962388e-306 1.78022342e-306 6.23058028e-307 1.33513938e-307]] 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [13]:
#14
a = np.array([0,12,45.21,34,99.91])
a =(a - 32)*5/9
print(a)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [5]:
#15
a = np.array([1.0000000+0.j,0.70710678+0.70710678j])
real = a.real
imag = a.imag
print(real)
print(imag)

[1.         0.70710678]
[0.         0.70710678]


In [11]:
#16
a = np.array([1,2,3,4])
print(len(a))
print(2**(len(a)))
print(len(a)*2**(len(a)))

4
16
64


In [2]:
#17
a1 = np.array([0,10,20,40,60])
a2 = np.array([0,40])
print(np.in1d(a1,a2))

[ True False False  True False]


In [3]:
#18
a = np.array([0,10,20,40,60])
b = np.array([10,30,40])
print(np.intersect1d(a,b))

[10 40]


In [18]:
#19
a = np.array([1,1,2,3]).reshape(2,2)
print(np.unique(a))

[1 2 3]


In [21]:
#20
a1 = np.array([0,10,20,40,60,80])
a2 = np.array([10,30,40,50,70,90])
print(np.setdiff1d(a1,a2))

[ 0 20 60 80]


In [23]:
#21
a1 = np.array([0,10,20,40,60,80])
a2 = np.array([10,30,40,50,70])
print(np.setxor1d(a1,a2))

[ 0 20 30 50 60 70 80]


In [24]:
#22
a1 = np.array([0,10,20,40,60,80])
a2 = np.array([10,30,40,50,70])
print(np.union1d(a1,a2))

[ 0 10 20 30 40 50 60 70 80]


In [91]:
#23
print(np.all([[True,1],[True,True]]))

True


In [92]:
#24
print(np.any([0,0]))

False


In [36]:
#25
a = [1,2,2,3,4]
a = np.array(a*3)
print(a)

[1 2 2 3 4 1 2 2 3 4 1 2 2 3 4]


In [37]:
#26
a = np.array([1,2,3,4])
print(np.repeat(a,2))

[1 1 2 2 3 3 4 4]


In [38]:
#27
a = np.array([1,2,3,4])
print(max(a))
print(min(a))

4
1


In [39]:
#28
a = np.array([1,2])
b = np.array([4,5])
print(a>b)
print(a>=b)
print(a<b)
print(a<=b)

[False False]
[False False]
[ True  True]
[ True  True]


In [93]:
#29 w3resource dan qara
a = np.array([[4,6],[2,1]])
print(np.sort(a,axis=0))
# a = a[::-1,::-1]
print(np.sort(a,axis=1))

[[2 1]
 [4 6]]
[[4 6]
 [1 2]]


In [2]:
#30 ?
first_names = ('Betsey','Sheley','Lanell','Genesis','Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')
x = np.lexsort((first_names,last_names))
print(x)

[0 1 2 3 4]


In [64]:
#31
a = np.array([[0,10,20],[20,30,40]])
print(a[a>10])
print(np.nonzero(a>10))

[20 20 30 40]
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [70]:
#32
a = np.arange(10)
np.savetxt('file.out',a,delimiter='//')
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [86]:
#33
n = np.array([1,2,3])
print(n)
print(n.size * n.itemsize)

[1 2 3]
12


In [100]:
#34
a = np.zeros((1,2))
a = a.astype('int32')
print(a)

[[0 0]]


In [7]:
#35
a = np.array([1,2,3,4,5,6,7,8,9,0])
b = a.reshape((2,5))
c = a.reshape((10,))
print(b)
print(c)

[[1 2 3 4 5]
 [6 7 8 9 0]]
[1 2 3 4 5 6 7 8 9 0]


In [8]:
#36
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])
a = a.flatten()
print(a)

[1 2 3 4 5 6 7 8 9 0]


In [12]:
#37
a = np.array([[1,2,3],[3,2,1]])
print(a.shape)
print(a.dtype)

(2, 3)
int32


In [13]:
#38


In [14]:
#39
a = np.array([1,2,3])
a = a.astype('float64')
print(a.dtype)

float64


In [15]:
#40
a = np.full((3,5),2)
print(a)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [21]:
#41
x = np.arange(4,dtype=np.int64)
x = np.full_like(x,10)
print(x)

[10 10 10 10]


In [3]:
#42
x = np.eye(3)
print(x)
print(x.shape)
print(x.ndim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
2


In [5]:
#43
x = np.diagflat([4,5,6,8])
print(x)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [6]:
#44
a = np.arange(50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [9]:
#45
b = np.linspace(2.5,6.5,30)
print(b)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [13]:
#46
a = np.logspace(2.,5.,20,endpoint=False)
print(a)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


In [17]:
#47
a = np.tri(4,3,-1)
print(a)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [26]:
#48
x = np.triu(np.arange(2,14).reshape(4,3),-1)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 0  9 10]
 [ 0  0 13]]


In [21]:
#49
a = np.eye(3)
a = a.reshape(1,9)
print(a)

[[1. 0. 0. 0. 1. 0. 0. 0. 1.]]


In [22]:
#50
a = np.array([[2,3,4],[5,6,7]])
b = a.flat[3]
print(b)

5


In [27]:
#51
a = np.array([[1,2,3]]).reshape(3,1)
print(a)

[[1]
 [2]
 [3]]


In [38]:
#52
x = np.zeros((2,3,4))
print(np.moveaxis(x,0,-1).shape)
print(np.moveaxis(x,-1,0).shape)

(3, 4, 2)
(4, 2, 3)


In [41]:
#53
x = np.zeros((2,3,4,5))
print(np.moveaxis(x,-1,1).shape)

(2, 5, 3, 4)


In [7]:
#54
x = 12.0
print(np.atleast_1d(x))
print(np.atleast_1d(1,[2,3]))

[12.]
[array([1]), array([2, 3])]


In [8]:
#55
x = 12.0
print(np.atleast_2d(x))
print(np.atleast_3d(x))

[[12.]]
[[[12.]]]


In [14]:
#56
x = np.zeros((3,4))
print(np.expand_dims(x,axis=1).shape)

(3, 1, 4)


In [18]:
#57
x = np.zeros((3,4,1))
print(np.squeeze(x).shape)

(3, 4)


In [ ]:
#58


In [50]:
#105
s = [i for i in range(2,9,2) if i%2]
print(s)
print('{1}{0}{1}'.format('cad','abra'))

[]
abracadabra


In [48]:
#106
a = np.array([10,20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
print(np.count_nonzero(a == 10))
print(np.count_nonzero(a == 20))
print(np.count_nonzero(a == 0))
print(np.count_nonzero(a == 30))

1
7
4
3


In [12]:
#107
nums = np.array([7,2,3,4,5])
print(np.percentile(nums,50))
print(np.percentile(nums,30))
print(np.percentile(nums,75))

4.0
3.2
5.0


In [40]:
#108
import PIL
img_data = PIL.Image.OPEN('rasm.png')
img_arr = np.array(img_data)
print(img_arr)

AttributeError: module 'PIL' has no attribute 'Image'