In [18]:
import numpy as np
from random import randint

In [20]:
a = 'salom hello katta'
b = np.array(['menga','ulkan'])
c = np.char.join(a,b)
print(c)

['msalom hello kattaesalom hello kattansalom hello kattagsalom hello kattaa'
 'usalom hello kattalsalom hello kattaksalom hello kattaasalom hello kattan']


In [26]:
np.char.strip([' Katta ',' Ulkan'],'n')

array([' Katta ', ' Ulka'], dtype='<U7')

In [30]:
np.char.replace([' Katta Ulkan'],'a','b',1)

array([' Kbtta Ulkan'], dtype='<U12')

In [50]:
np.char.count([' Katta ',' Ulkan'],['a','n'],[0,1],[2,3])

array([0, 0])

In [52]:
np.char.find(['sdf','dslfad','sdhkjg'],'s')

array([0, 1, 0])

In [57]:
np.char.index(['sdf','dslfad','sdhkjg'],'s')

array([0, 1, 0])

In [59]:
np.char.endswith(['Katta','ulkan'],['a','b'],[1,2],[5,4])

array([ True, False])

In [62]:
np.char.multiply(['katta'],3)

array(['kattakattakatta'], dtype='<U15')

In [2]:
import cv2
import numpy as np

In [6]:
a=np.random.randint(0,255,(400,400,3))
a=a.astype('float')/255.0
print(a)
cv2.imshow('Dars',a)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[0.7254902  0.95294118 0.18039216]
  [0.56470588 0.3254902  0.89019608]
  [0.37647059 0.72941176 0.90588235]
  ...
  [0.29803922 0.9372549  0.56078431]
  [0.63921569 0.17647059 0.15686275]
  [0.84313725 0.8627451  0.97254902]]

 [[0.63921569 0.26666667 0.24705882]
  [0.24705882 0.84705882 0.91372549]
  [0.1254902  0.01568627 0.46666667]
  ...
  [0.00392157 0.90980392 0.14117647]
  [0.60392157 0.07843137 0.81960784]
  [0.81568627 0.40784314 0.76078431]]

 [[0.87843137 0.70588235 0.8627451 ]
  [0.48235294 0.97647059 0.33333333]
  [0.59215686 0.53333333 0.40784314]
  ...
  [0.70588235 0.4745098  0.55294118]
  [0.96862745 0.40784314 0.22352941]
  [0.82352941 0.27058824 0.16470588]]

 ...

 [[0.85882353 0.7372549  0.69019608]
  [0.43137255 0.59607843 0.88235294]
  [0.08627451 0.56470588 0.02745098]
  ...
  [0.4        0.94509804 0.96078431]
  [0.09019608 0.94509804 0.89411765]
  [0.63529412 0.49411765 0.80784314]]

 [[0.21176471 0.43137255 0.36470588]
  [0.06666667 0.1254902  0.25490196]


In [18]:
a=np.random.randint(0,255,10000)
a.resize(100,100)
print(a)
print()
b=a[:,:-1]-a[:,1:]
a[:,:-1] = b
a[:,-1]=0
print(a)
print(a.shape)

[[136 116  44 ...  23  95   9]
 [233 242 146 ... 151 176 115]
 [148 218 118 ...  47  71 134]
 ...
 [154  43 153 ...  41 132  21]
 [124  39 217 ... 216 204  78]
 [ 30  60 181 ... 216 103 197]]

[[  20   72  -44 ...  -72   86    0]
 [  -9   96  -53 ...  -25   61    0]
 [ -70  100  -53 ...  -24  -63    0]
 ...
 [ 111 -110  148 ...  -91  111    0]
 [  85 -178  196 ...   12  126    0]
 [ -30 -121   87 ...  113  -94    0]]
(100, 100)


In [4]:
a=np.random.randint(0,255,10000)
a.resize(100,100)
print(a)
print()
b=a[:-1,:]-a[1:,:]
a[:-1,:]=b
a[-1,]=0
print(a)
print(a.shape)

[[202 215  60 ... 205 118 253]
 [163 226 251 ... 106 231  93]
 [ 89  70  24 ... 167 239   9]
 ...
 [ 91 124   9 ... 171 123 160]
 [229 107  97 ... 158  36 117]
 [230 241  62 ... 179 222 145]]

[[  39  -11 -191 ...   99 -113  160]
 [  74  156  227 ...  -61   -8   84]
 [  66 -115  -79 ...  154  145 -162]
 ...
 [-138   17  -88 ...   13   87   43]
 [  -1 -134   35 ...  -21 -186  -28]
 [   0    0    0 ...    0    0    0]]
(100, 100)


In [9]:
a = np.array([[1,2,3,4],[1,2,3,4],[2,3,3,4]]).reshape(4,3)
print(a)
print()
print(a.base)

[[1 2 3]
 [4 1 2]
 [3 4 2]
 [3 3 4]]

[[1 2 3 4]
 [1 2 3 4]
 [2 3 3 4]]


In [17]:
a=np.array([[[1,2,3,4,5],[6,7,8,9,10]]],ndmin=4)
print(a)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]]]


In [6]:
print(np.finfo('float32'))

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
---------------------------------------------------------------



In [46]:
a=a[:-1]-a[1:]
a+=[0]*1000
print(a)
print(a.shape)

[[  31    6  117 ... -141  -75    5]
 [   5  -70 -150 ...   37  -20   80]
 [  36  -16  143 ...   68   16   -2]
 ...
 [ -65  -10   -4 ...  -22  -31 -112]
 [  43   -1    6 ...  -38  -66   93]
 [-169 -100   43 ...   90  -77  -74]]
(999, 1000)


In [47]:
a=np.random.randint(0,255,1000000)
a.resize((1000,1000))
print(a)

[[213  90  60 ...  88 183 220]
 [ 65  45 184 ... 174 193  76]
 [158  94 156 ...  95 143 183]
 ...
 [249 115 120 ...  19  48 164]
 [ 93 238 191 ...  67  73 253]
 [ 47 207  49 ...  84 107  47]]


In [49]:
b=a[:,:-1]-a[:,1:]

print(a)
print(a.shape)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [23]:
for i in range(999):
    a[:,i]-=a[:,i+1]
a[:,-1]=0
print(a)

[[ -38    7    3 ...  123   -6    0]
 [ -34   -7  -18 ...  -60   80    0]
 [  97   -2  -17 ...   -8  125    0]
 ...
 [ -35   70  -56 ... -143   -9    0]
 [ -25   61 -155 ...  -16 -152    0]
 [-193  179   22 ... -187   61    0]]


In [25]:
for i in range(999):
    a[i,:]-=a[i+1,:]
a[-1,:]=0
print(a)

[[-179   65  167 ...  105  -61   64]
 [  55  -61   -8 ... -197  -98  -51]
 [-120  104   -5 ...  207  185  -55]
 ...
 [  51 -109  -30 ... -170 -158   45]
 [ -39   81   90 ...  128   88   -8]
 [   0    0    0 ...    0    0    0]]


In [21]:
print(a.shape)

(1000, 1000)


In [11]:
print(np.std(a))

73.54766737901014


In [10]:
#1
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
a*=10
print(a)

m=2
n=3
[[10 20 30]
 [40 50 60]]


In [16]:
a=np.array([1,2,3])
print(np.full_like(a))
print(a)

TypeError: _full_like_dispatcher() missing 1 required positional argument: 'fill_value'

In [17]:
print(np.l((np.arange(0,20,5))))

[[ 0  5 10 15]]


In [19]:
#7
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
print(a)
k=int(input('k='))
print(a[k])

m=4
n=5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
k=2
[11 12 13 14 15]


In [21]:
#8
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
print(a)
k=int(input('k='))
print(a[:,k])

m=4
n=5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
k=2
[ 3  8 13 18]


In [23]:
#9
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
print(a)
print()
print(a[::2])

m=4
n=5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [ ]:
#10
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
print(a)
print()
print(a[1::2])

In [4]:
#11
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
print(a)
print()

m=2
n=100
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
   37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
   55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
   73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
   91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
  119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
  137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154
  155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
  173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190
  191 192 193 194 195 196 197 198 199 200]]



In [13]:
#17
from math import factorial 
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
print(a)
print()
k=int(input('k='))
print(sum(a[k]))
print(np.prod(a[k]))

m=4
n=5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

k=1
40
30240


In [14]:
#18
from math import factorial 
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
print(a)
print()
k=int(input('k='))
print(sum(a[:,k]))
print(np.prod(a[k]))

m=4
n=5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

k=2
42
360360


In [12]:
#19
from math import factorial 
m=int(input('m='))
n=int(input('n='))
a=np.arange(1,m*n+1).reshape(m,n)
print(a)
print()
for i in range(m):
    print(f'Sum a{i}',sum(a[i]))
    print(f'Kopaytma a{i}',np.prod(a[i]))

m=4
n=5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sum a0 15
Kopaytma a0 120
Sum a1 40
Kopaytma a1 30240
Sum a2 65
Kopaytma a2 360360
Sum a3 90
Kopaytma a3 1860480


In [15]:
#20
for i in range(n):
    print(np.prod(a[:,i]))

1056
2856
5616
9576
15000


In [20]:
#21
for i in range(m):
    print(sum(a[i,1::2])/(m//2))

3.0
8.0
13.0
18.0


In [22]:
#22
for i in range(n):
     print(sum(a[::2,i]))

12
14
16
18
20


In [46]:
#29
def func(a):
    s=0
    for k in a:
        if k<np.mean(a):
            s+=1
    return s
for i in range(m):
    print(func(a[i]))

2
2
2
2


In [47]:
#30
def func(a):
    s=0
    for k in a:
        if k<np.mean(a):
            s+=1
    return s
for i in range(n):
    print(func(a[:,i]))

2
2
2
2
2


In [50]:
#31
satr=abs(np.mean(a)-np.mean(a[0]))
s_i=0
ustun=abs(np.mean(a)-np.mean(a[:,0]))
u_i=0
for i in range(m):
    if satr>abs(np.mean(a)-np.mean(a[i])):
        satr=abs(np.mean(a)-np.mean(a[i]))
        s_i=i
print(s_i)
for i in range(n):
    if ustun>abs(np.mean(a)-np.mean(a[:,i])):
        ustun=abs(np.mean(a)-np.mean(a[:,i]))
        u_i=i
print(u_i)

1
2


In [3]:
class Talaba:
    def __init__(self,ismi,yoshi):
        self.ismi = ismi
        self.yoshi = yoshi
        
a=Talaba('K',20)
b=Talaba('A',25)
c=Talaba('Z',19)

print(sorted([a.yoshi,b.yoshi,c.yoshi]))

[19, 20, 25]
